//! The guest-to-host call boundary.
//!
//! Roadmap phase 0b, kept because it answered its question and the answer is
//! load-bearing.
//!
//! # The question
//!
//! Guest code calls an imported function. That call has to land on host code and come
//! back with the arguments intact. Everything above this - the loader, relocations,
//! every subsystem shim - assumes it works. If the calling convention or the stack
//! discipline is wrong, phase 4 is an expensive place to find out.
//!
//! # The answer, and why it is not obvious
//!
//! The guest is FreeBSD-derived, so it calls with the **System V** convention:
//! integer arguments in `rdi, rsi, rdx, rcx, r8, r9`, return in `rax`.
//!
//! On Windows the host's native convention is different - arguments in
//! `rcx, rdx, r8, r9`, and a 32-byte shadow space the caller must reserve. A guest
//! calling an ordinary Rust `extern "C"` function on Windows would therefore pass
//! arguments in the wrong registers, and the failure would be silent: the callee reads
//! whatever happened to be in `rcx`.
//!
//! The fix is that host functions the guest can reach are declared
//! **`extern "sysv64"`**, so the compiler emits a callee using the guest's convention.
//! This module proves that end to end by executing real machine code.
//!
//! # What this is not
//!
//! Not a loader and not a thunk generator. It reserves plain executable memory at
//! whatever address the OS likes, because the question is about *convention*, not
//! placement - placement is phase 3's problem and already answered.

use std::io;

pub mod enter;
pub mod exec;
pub mod thread_pointer;

pub use enter::enter_guest;

pub use exec::ExecutableBuffer;

/// The six integer argument registers System V passes arguments in, in order.
pub const SYSV_INT_ARG_REGISTERS: [&str; 6] = ["rdi", "rsi", "rdx", "rcx", "r8", "r9"];

/// A host function reachable from guest code.
///
/// **`extern "sysv64"` is the whole point.** The guest calls with System V; declaring
/// the callee that way makes the compiler agree, on every host including Windows,
/// where the native convention differs.
pub type GuestCallable = extern "sysv64" fn(u64, u64, u64, u64, u64, u64) -> u64;

/// Emits machine code that calls `target` with six arguments and returns its result.
///
/// The generated code is System V: it loads the six argument registers with the given
/// values, calls through `rax`, and returns whatever the callee left in `rax`.
///
/// Deliberately hand-assembled rather than generated by a crate: the point is to prove
/// the boundary works with no assembler in the way, and the sequence is short enough
/// to read.
pub fn emit_call_with_six_args(target: u64, args: [u64; 6]) -> Vec<u8> {
    // `movabs r64, imm64` for each argument register, in System V order.
    // REX.W + B8+rd, where rd is the register number.
    const MOVABS: [[u8; 2]; 6] = [
        [0x48, 0xBF], // rdi
        [0x48, 0xBE], // rsi
        [0x48, 0xBA], // rdx
        [0x48, 0xB9], // rcx
        [0x49, 0xB8], // r8
        [0x49, 0xB9], // r9
    ];

    let mut code = Vec::new();
    for (opcode, value) in MOVABS.iter().zip(args) {
        code.extend_from_slice(opcode);
        code.extend_from_slice(&value.to_le_bytes());
    }

    // movabs rax, target
    code.extend_from_slice(&[0x48, 0xB8]);
    code.extend_from_slice(&target.to_le_bytes());
    // call rax
    code.extend_from_slice(&[0xFF, 0xD0]);
    // ret
    code.push(0xC3);

    code
}

/// Emits machine code that returns a constant, touching nothing else.
///
/// The smallest possible proof that emitted bytes execute at all - worth having
/// separately, so a failure in the call sequence can be told apart from a failure to
/// execute anything.
pub fn emit_return_constant(value: u64) -> Vec<u8> {
    let mut code = Vec::new();
    code.extend_from_slice(&[0x48, 0xB8]); // movabs rax, imm64
    code.extend_from_slice(&value.to_le_bytes());
    code.push(0xC3); // ret
    code
}

/// Runs emitted code that takes no arguments and returns a `u64`.
///
/// # Errors
///
/// Fails if executable memory cannot be obtained.
pub fn run(code: &[u8]) -> io::Result<u64> {
    let buffer = ExecutableBuffer::new(code)?;
    // SAFETY: the buffer holds exactly the bytes emitted above, which end in `ret` and
    // touch only volatile registers. The transmute target matches the System V
    // convention the emitted code uses.
    let f: extern "sysv64" fn() -> u64 = unsafe { std::mem::transmute(buffer.as_ptr()) };
    Ok(f())
}

#[cfg(test)]
mod tests {
    use super::{GuestCallable, emit_call_with_six_args, emit_return_constant, run};
    use std::sync::atomic::{AtomicU64, Ordering};

    /// Records what the last call received, so a test can assert on it.
    static SEEN: [AtomicU64; 6] = [
        AtomicU64::new(0),
        AtomicU64::new(0),
        AtomicU64::new(0),
        AtomicU64::new(0),
        AtomicU64::new(0),
        AtomicU64::new(0),
    ];

    /// A host function guest code can call.
    ///
    /// `extern "sysv64"` is what makes this correct on Windows, where the native
    /// convention would put these arguments in different registers entirely.
    extern "sysv64" fn host_target(
        arg0: u64,
        arg1: u64,
        arg2: u64,
        arg3: u64,
        arg4: u64,
        arg5: u64,
    ) -> u64 {
        for (slot, value) in SEEN.iter().zip([arg0, arg1, arg2, arg3, arg4, arg5]) {
            slot.store(value, Ordering::SeqCst);
        }
        0x5AFE_0000_0000_5AFE
    }

    #[test]
    fn emitted_code_executes_at_all() {
        // Separated from the call test so "cannot execute" and "call convention wrong"
        // are distinguishable failures rather than one confusing one.
        let got = run(&emit_return_constant(0x1234_5678_9ABC_DEF0)).expect("execute");
        assert_eq!(got, 0x1234_5678_9ABC_DEF0);
    }

    /// Serialises the tests that read and write [`SEEN`].
    ///
    /// **They share one global array and `cargo` runs them on parallel threads**, so
    /// without this each can observe the other's arguments. That is the whole of the
    /// intermittent failure recorded in `docs/BACKLOG.md` as fixed-address contention
    /// between `orbistoun-abi` and `orbistoun-mem`: the diagnosis was wrong. The
    /// observed value gives it away - `argument 0 arrived wrong: left 3` is not a
    /// corrupted address, it is `the_call_can_be_made_repeatedly` on its third round,
    /// which writes exactly 3 there.
    ///
    /// A lock rather than separate arrays because the array is what the emitted code
    /// writes into, and giving each test its own would mean two host targets and two
    /// copies of the thing being tested.
    static SEEN_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

    /// Takes [`SEEN_LOCK`], ignoring poisoning.
    ///
    /// A failing test poisons the mutex, and propagating that turns one real failure
    /// into two - the second reported as a panic in the lock rather than as what it
    /// actually is, which is a worse thing to read at the top of a gate run.
    fn seen_lock() -> std::sync::MutexGuard<'static, ()> {
        SEEN_LOCK
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner)
    }

    #[test]
    fn a_guest_call_lands_on_the_host_with_all_six_arguments_intact() {
        let _serialised = seen_lock();
        // The question phase 0b exists to answer. If this passes, the loader can be
        // built on the assumption that resolving an import to a host function works.
        let target: GuestCallable = host_target;
        let args = [
            0x1111_1111_1111_1111,
            0x2222_2222_2222_2222,
            0x3333_3333_3333_3333,
            0x4444_4444_4444_4444,
            0x5555_5555_5555_5555,
            0x6666_6666_6666_6666,
        ];

        let code = emit_call_with_six_args(target as usize as u64, args);
        let returned = run(&code).expect("execute");

        assert_eq!(
            returned, 0x5AFE_0000_0000_5AFE,
            "the return value must come back in rax"
        );
        for (index, expected) in args.iter().enumerate() {
            assert_eq!(
                SEEN[index].load(Ordering::SeqCst),
                *expected,
                "argument {index} ({}) arrived wrong - the calling convention disagrees",
                super::SYSV_INT_ARG_REGISTERS[index]
            );
        }
    }

    #[test]
    fn the_emitted_sequence_is_the_expected_length() {
        // Six 10-byte movabs, one 10-byte movabs for the target, call, ret.
        assert_eq!(
            emit_call_with_six_args(0, [0; 6]).len(),
            6 * 10 + 10 + 2 + 1
        );
        assert_eq!(emit_return_constant(0).len(), 10 + 1);
    }

    #[test]
    fn the_call_can_be_made_repeatedly() {
        let _serialised = seen_lock();
        // A one-shot success could be luck with leftover register state; two calls
        // with different arguments cannot be.
        let target: GuestCallable = host_target;
        for round in 1..=3_u64 {
            let args = [round, round * 2, round * 3, round * 4, round * 5, round * 6];
            run(&emit_call_with_six_args(target as usize as u64, args)).expect("execute");
            for (index, expected) in args.iter().enumerate() {
                assert_eq!(
                    SEEN[index].load(Ordering::SeqCst),
                    *expected,
                    "round {round}"
                );
            }
        }
    }
}
