[title]
id = "PPSA25872"
name = "Terminator 2D: NO FATE"
content_version = "01.002.000"
master_version = "01.00"

[compat]

[settings]

[status]
reach = "flipped"
outcome = "image+0x3b383b"
imports = 192
calls = 339539
standing = 100
default_return = "unimplemented"
frames = 1
unanswered = 14
limit_seconds = 2
build = "0.1.0"
measured_on = "2026-09-13"

[experiment]
reach = "entered"
outcome = "image+0x17554a3"
imports = 155
calls = 321979
standing = 100
default_return = "unimplemented"
overrides = 2
propping = 2
unanswered = 1
limit_seconds = 20
build = "v0.1.0 - 34ff307-dirty"
measured_on = "2026-09-25"
