[title]
id = "PPSA04263"
name = "Grand Theft Auto V"
content_version = "01.010.002"
master_version = "01.00"

[compat]

[settings]

[status]
reach = "entered"
outcome = "image+0x19676d7"
imports = 75
calls = 30460
standing = 100
default_return = "unimplemented"
unanswered = 5
limit_seconds = 20
build = "v0.1.0 - 712d8c6-dirty"
measured_on = "2026-09-21"

[experiment]
reach = "entered"
outcome = "image+0x19676d7"
imports = 75
calls = 30462
standing = 100
default_return = "unimplemented"
overrides = 2
propping = 2
unanswered = 4
limit_seconds = 20
build = "v0.1.0 - cb409d0-dirty"
measured_on = "2026-09-22"
