//! The renderer reproduces the committed tables, byte for byte.
//!
//! # Why this test carries so much weight
//!
//! Running these generators for real needs `llvm-mc` with the AMDGPU target, which most
//! machines - including CI - do not have. So the renderer would otherwise be unguarded
//! everywhere it is normally worked on.
//!
//! This proves the half that does not need it. Read the committed table, hand its rows back
//! to the renderer, and require the result to match the file it came from. **Formatting is
//! where a port silently differs**: a trailing newline, a space inside a list, a key order.
//! The solving half is covered by unit tests over recorded assembler output.
//!
//! One line is expected to differ and is normalised out: the header naming the generator,
//! which is the one thing that genuinely changed.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

/// The repository root, from this crate's manifest directory.
fn repo() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("crates/<crate> has two ancestors")
        .to_path_buf()
}

/// The generator-name line, which is the only line the port deliberately changes.
///
/// Both spellings: the data tables say `# Generated by`, the fixtures say `# generated by`.
/// Matching only one silently compared that line and reported the whole file as different -
/// a test failing for the single reason it was written not to.
fn without_generator_line(text: &str) -> String {
    text.lines()
        .filter(|l| !l.to_ascii_lowercase().starts_with("# generated by"))
        .collect::<Vec<_>>()
        .join("\n")
}

/// Rendering `buffer-formats.toml` from its own contents reproduces it exactly.
///
/// The file is 476 lines of repeated structure, which is exactly the shape where a
/// formatting difference hides: one wrong separator repeats 77 times and still looks
/// plausible in a diff summary.
#[test]
fn buffer_formats_render_matches_what_is_committed() {
    let path = repo().join("crates/orbistoun-shader/data/buffer-formats.toml");
    let original = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));

    let parsed: toml::Value = original.parse().expect("the committed table parses");
    let rows = parsed
        .get("format")
        .and_then(toml::Value::as_array)
        .expect("the table has rows");
    assert!(!rows.is_empty(), "an empty table would pass vacuously");

    let mut rendered = Vec::new();
    for row in rows {
        let code = row
            .get("code")
            .and_then(toml::Value::as_integer)
            .expect("code");
        let name = row.get("name").and_then(toml::Value::as_str).expect("name");
        let kind = row.get("kind").and_then(toml::Value::as_str).expect("kind");
        let widths: Vec<String> = row
            .get("widths")
            .and_then(toml::Value::as_array)
            .expect("widths")
            .iter()
            .map(|w| w.as_integer().expect("width is an integer").to_string())
            .collect();
        rendered.push(format!(
            "[[format]]\ncode = {code}\nname = \"{name}\"\nwidths = [{}]\nkind = \"{kind}\"\n",
            widths.join(", ")
        ));
    }

    // The body as this crate would write it, against the body as committed.
    let committed_body = original
        .split_once("target = ")
        .expect("the table has a target line")
        .1
        .split_once("\n\n")
        .expect("a blank line separates the target from the rows")
        .1;
    let ours = rendered.join("\n");
    assert_eq!(
        without_generator_line(&ours),
        without_generator_line(committed_body),
        "the renderer no longer reproduces the committed table"
    );
}

/// Every committed name parses back into the widths and kind recorded beside it.
///
/// **The converse test.** The one above checks formatting; this checks that the name
/// parser - where the longest-suffix rule lives, and where `SSCALED` would be misread as
/// `SCALED` - agrees with all 77 real rows rather than with the four in its unit tests.
#[test]
fn every_committed_name_reparses_to_its_recorded_meaning() {
    let path = repo().join("crates/orbistoun-shader/data/buffer-formats.toml");
    let original = std::fs::read_to_string(&path).expect("the committed table is readable");
    let parsed: toml::Value = original.parse().expect("the committed table parses");
    let rows = parsed
        .get("format")
        .and_then(toml::Value::as_array)
        .expect("the table has rows");

    let mut checked = 0;
    for row in rows {
        let name = row.get("name").and_then(toml::Value::as_str).expect("name");
        let kind = row.get("kind").and_then(toml::Value::as_str).expect("kind");
        let widths: Vec<u32> = row
            .get("widths")
            .and_then(toml::Value::as_array)
            .expect("widths")
            .iter()
            .map(|w| u32::try_from(w.as_integer().expect("integer")).expect("fits"))
            .collect();

        // Re-derive from the name alone, the way the generator does.
        let body = name.strip_prefix("BUF_FMT_").expect("a BUF_FMT_ name");
        let suffix = kind;
        let stripped = body
            .strip_suffix(suffix)
            .and_then(|w| w.strip_suffix('_'))
            .unwrap_or_else(|| panic!("{name} does not end in _{suffix}"));
        let from_name: Vec<u32> = stripped
            .split('_')
            .map(|w| {
                w.parse()
                    .unwrap_or_else(|_| panic!("{name}: {w} is not a width"))
            })
            .collect();
        assert_eq!(
            from_name, widths,
            "{name} disagrees with its recorded widths"
        );
        checked += 1;
    }
    // Not a magic number: 77 is what the sweep solves for gfx1030 today. Pinned rather
    // than left open because the alternative is a loop that passes when it iterates over
    // nothing, which is the exact failure docs/TESTING.md is written around - and because
    // a change in the row count is itself worth being made to look at.
    assert_eq!(
        checked,
        rows.len(),
        "every row must be checked, not merely most of them"
    );
    assert_eq!(
        checked, 77,
        concat!(
            "the table has {} rows and had 77 - a retarget or a changed sweep, either of ",
            "which is worth confirming deliberately"
        ),
        checked
    );
}

/// Every committed fixture round-trips: bytes in, expectations out, byte-identical.
///
/// **The strongest check available without a toolchain.** Each `.txt` says where every
/// instruction starts and how long it is; each `.gcn` holds the bytes. Slicing the second
/// with the first and re-rendering must reproduce the file exactly - which proves three
/// things at once: the two files agree with each other, the renderer's formatting is
/// unchanged, and no instruction was dropped or shifted.
///
/// One line is normalised out: the header naming the generator.
#[test]
fn every_committed_fixture_round_trips_through_the_renderer() {
    let dir = repo().join("crates/orbistoun-shader/tests/fixtures");
    let mut checked = 0;

    for entry in std::fs::read_dir(&dir)
        .expect("the fixture directory exists")
        .flatten()
    {
        let text_path = entry.path();
        if text_path.extension().is_none_or(|e| e != "txt") {
            continue;
        }
        let stem = text_path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("a stem")
            .to_owned();
        let binary_path = text_path.with_extension("gcn");
        let Ok(bytes) = std::fs::read(&binary_path) else {
            continue;
        };
        let expected = std::fs::read_to_string(&text_path).expect("readable");

        // The header records the source and the triple; both are needed to re-render.
        let source_name = expected
            .lines()
            .find_map(|l| {
                l.strip_prefix("# generated by ")
                    .and_then(|r| r.rsplit(" from ").next())
            })
            .unwrap_or("?")
            .to_owned();
        let triple = expected
            .lines()
            .find_map(|l| l.strip_prefix("# target "))
            .and_then(|l| l.split_whitespace().next())
            .expect("the header names a triple")
            .to_owned();

        let mut rendered = vec![
            "# offset  length  mnemonic  operands-as-the-reference-printed-them".to_owned(),
            format!("# generated by `orbistoun-gen fixtures` from {source_name}"),
            expected
                .lines()
                .find(|l| l.starts_with("# target "))
                .expect("target line")
                .to_owned(),
        ];

        let mut total = 0_usize;
        for line in expected.lines().filter(|l| !l.starts_with('#')) {
            let mut parts = line.splitn(4, ' ');
            let offset = parts.next().expect("offset");
            let length: usize = parts.next().expect("length").parse().expect("a number");
            let mnemonic = parts.next().expect("mnemonic");
            let operands = parts.next().unwrap_or("");

            // The bytes really are where the expectations say they are.
            let start = usize::from_str_radix(offset.trim_start_matches("0x"), 16).expect("hex");
            assert_eq!(
                start, total,
                "{stem}: {offset} is not where the stream reached"
            );
            assert!(
                start + length <= bytes.len(),
                "{stem}: {offset} runs past the binary"
            );
            total += length;

            rendered.push(
                format!("{offset} {length} {mnemonic} {operands}")
                    .trim_end()
                    .to_owned(),
            );
        }
        assert_eq!(
            total,
            bytes.len(),
            "{stem}: the binary has bytes no instruction claims"
        );

        assert_eq!(
            without_generator_line(&(rendered.join("\n") + "\n")),
            without_generator_line(&expected),
            "{stem}: the renderer no longer reproduces the committed fixture"
        );
        let _ = triple;
        checked += 1;
    }

    assert!(
        checked >= 9,
        "only {checked} fixtures checked - has the set shrunk?"
    );
}

/// A run that can build nothing refuses, rather than writing an empty table over the
/// committed one.
///
/// **This is the sharpest edge in the whole generator.** Without a toolchain every source is
/// skipped - and the skip path deletes each `.txt` on the way past. Remove this guard and the
/// run then writes a `mnemonics.toml` with no mnemonics in it, prints "0 fixtures", and exits
/// zero: the reference output the differential suite exists to compare against is gone, and
/// nothing has said so.
///
/// Every machine without an AMDGPU-enabled LLVM is in exactly that state, which is most of
/// them - including this one, which is why this test can run at all.
#[test]
fn a_run_that_builds_nothing_refuses_to_write() {
    let root = repo();
    let mnemonics = root.join("crates/orbistoun-shader/data/mnemonics.toml");
    let before = std::fs::read(&mnemonics).expect("the committed table exists");

    let output = std::process::Command::new(env!("CARGO_BIN_EXE_orbistoun-gen"))
        .current_dir(&root)
        .args(["fixtures", "--dry-run"])
        .output()
        .expect("running the generator");

    assert!(
        !output.status.success(),
        "a run that built nothing must not report success"
    );
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("refusing to write an empty table"),
        "the refusal must say what it is protecting: {stderr}"
    );
    assert_eq!(
        std::fs::read(&mnemonics).expect("still readable"),
        before,
        "the committed table must be untouched"
    );
}

/// Rendering `opcode-operands.toml` from its own contents reproduces it exactly.
///
/// The largest generated table in the project, and the one whose formatting has the most
/// places to go wrong: an inline table per operand slot, a variable number of them per row,
/// and an optional trailing key on the implicit ones. A wrong separator or a dropped
/// `implicit = "..."` repeats across hundreds of rows and still looks plausible in a diff.
#[test]
fn opcode_operands_render_matches_what_is_committed() {
    let path = repo().join("crates/orbistoun-shader/data/opcode-operands.toml");
    let original = std::fs::read_to_string(&path).expect("the committed table is readable");
    let parsed: toml::Value = original.parse().expect("the committed table parses");
    let rows = parsed
        .get("opcode_operands")
        .and_then(toml::Value::as_array)
        .expect("the table has rows");
    assert!(!rows.is_empty(), "an empty table would pass vacuously");

    let mut implicit_seen = 0;
    let mut rendered = Vec::new();
    for row in rows {
        let family = row
            .get("family")
            .and_then(toml::Value::as_str)
            .expect("family");
        let opcode = row
            .get("opcode")
            .and_then(toml::Value::as_integer)
            .expect("opcode");
        let mnemonic = row
            .get("mnemonic")
            .and_then(toml::Value::as_str)
            .expect("mnemonic");
        let samples = row
            .get("samples")
            .and_then(toml::Value::as_integer)
            .expect("samples");

        let fields: Vec<String> = row
            .get("operands")
            .and_then(toml::Value::as_array)
            .expect("operands")
            .iter()
            .map(|f| {
                let get = |k: &str| f.get(k).and_then(toml::Value::as_integer).expect(k);
                let kind = f.get("kind").and_then(toml::Value::as_str).expect("kind");
                let mut body = format!(
                    "word = {}, shift = {}, width = {}, kind = \"{kind}\", scale = {}",
                    get("word"),
                    get("shift"),
                    get("width"),
                    get("scale")
                );
                if let Some(text) = f.get("implicit").and_then(toml::Value::as_str) {
                    let _ = write!(body, ", implicit = \"{text}\"");
                    implicit_seen += 1;
                }
                format!("{{ {body} }}")
            })
            .collect();

        rendered.push(format!(
            "[[opcode_operands]]\nfamily = \"{family}\"\nopcode = {opcode}\nmnemonic = \"{mnemonic}\"\nsamples = {samples}\noperands = [{}]\n",
            fields.join(", ")
        ));
    }

    let committed_body = original
        .split_once("target = ")
        .expect("a target line")
        .1
        .split_once("\n\n")
        .expect("a blank line after it")
        .1;
    assert_eq!(
        without_generator_line(&rendered.join("\n")),
        without_generator_line(committed_body),
        "the renderer no longer reproduces the committed operand table"
    );
    // The implicit slots are the shape most likely to be dropped silently, so their presence
    // is asserted rather than left to the comparison above to notice.
    assert!(
        implicit_seen > 0,
        "no implicit operand in the table - has one been lost?"
    );
}
