//! What a typed buffer access's format field means.
//!
//! A typed buffer access carries a seven-bit format in bits 25:19 of its first word: the
//! component count, each component's width, and how the bits become a number. The table
//! is generated by `orbistoun-gen buffer-formats`, which asks the reference assembler for
//! each code's name and reads the encoding back to confirm it. A row records the format's
//! meaning, not whether the translator handles it.

use serde::Deserialize;

use crate::ShaderError;

/// How a component's bits become a number.
///
/// Spelled as the reference assembler spells it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize)]
pub enum ComponentKind {
    #[serde(rename = "UNORM")]
    /// An unsigned integer scaled so its full range becomes 0.0 to 1.0.
    Unorm,
    #[serde(rename = "SNORM")]
    /// A signed integer scaled so its full range becomes -1.0 to 1.0.
    Snorm,
    #[serde(rename = "USCALED")]
    /// An unsigned integer converted to the float of the same value.
    Uscaled,
    #[serde(rename = "SSCALED")]
    /// A signed integer converted to the float of the same value.
    Sscaled,
    #[serde(rename = "UINT")]
    /// An unsigned integer, used as an integer.
    Uint,
    #[serde(rename = "SINT")]
    /// A signed integer, used as an integer.
    Sint,
    #[serde(rename = "FLOAT")]
    /// Floating point, in the width the component gives.
    Float,
    #[serde(rename = "SRGB")]
    /// An unsigned integer in the sRGB transfer function rather than a linear one.
    Srgb,
}

/// One format code's meaning.
#[derive(Debug, Clone, Deserialize)]
pub struct BufferFormat {
    /// The value of the format field.
    pub code: u32,
    /// The name the reference prints, carried so a row can be checked by eye.
    pub name: String,
    /// One entry per component, in bits, listed highest bits first, as the name lists them.
    ///
    /// `BUF_FMT_10_11_11_FLOAT` is `[10, 11, 11]`: the component at bit 0 (`x`) is the last
    /// entry, eleven bits wide. Reading the first entry as `x` mirrors the packing, which
    /// only shows on formats with unequal widths.
    pub widths: Vec<u32>,
    /// How those bits become a number.
    pub kind: ComponentKind,
}

impl BufferFormat {
    /// Whether every component is a whole 32-bit word.
    ///
    /// Such a format moves words unchanged, like an untyped access per component; anything
    /// narrower is unpacked from within a word and converted.
    pub fn is_plain_words(&self) -> bool {
        !self.widths.is_empty() && self.widths.iter().all(|width| *width == 32)
    }

    /// How many components the format moves.
    pub fn components(&self) -> usize {
        self.widths.len()
    }
}

#[derive(Debug, Deserialize, Default)]
struct FormatFile {
    #[serde(default)]
    target: String,
    #[serde(default)]
    format: Vec<BufferFormat>,
}

/// Every format code with a meaning.
#[derive(Debug, Clone, Default)]
pub struct FormatTable {
    formats: Vec<BufferFormat>,
}

impl FormatTable {
    /// Where the format field sits in the first word.
    ///
    /// The generator writes a code, reads the field back, and records a row only if they
    /// agree.
    pub const SHIFT: u32 = 19;
    /// How wide that field is.
    pub const WIDTH: u32 = 7;

    /// The table shipped with this crate.
    pub fn builtin() -> Result<Self, ShaderError> {
        Self::load(include_str!("../data/buffer-formats.toml"))
    }

    /// Parses a format table.
    pub fn load(text: &str) -> Result<Self, ShaderError> {
        let file: FormatFile =
            toml::from_str(text).map_err(|e| ShaderError::Table(e.to_string()))?;
        let _ = file.target;
        let mut formats = file.format;
        formats.sort_by_key(|format| format.code);
        // A duplicated code is a generator fault; refuse it rather than pick a row.
        if let Some(pair) = formats.windows(2).find(|pair| pair[0].code == pair[1].code) {
            return Err(ShaderError::Table(format!(
                "format code {} is named both {} and {}",
                pair[0].code, pair[0].name, pair[1].name
            )));
        }
        Ok(Self { formats })
    }

    /// Extracts the format field from an instruction's first word.
    pub const fn field(word: u32) -> u32 {
        (word >> Self::SHIFT) & ((1 << Self::WIDTH) - 1)
    }

    /// What a code means, or `None` if it means nothing.
    ///
    /// `None` covers the explicitly invalid code and the reserved codes the reference has
    /// no name for. A shader carrying either is wrong, and is reported as such.
    pub fn get(&self, code: u32) -> Option<&BufferFormat> {
        self.formats
            .binary_search_by_key(&code, |format| format.code)
            .ok()
            .map(|index| &self.formats[index])
    }

    /// Every format with a meaning, by code.
    pub fn formats(&self) -> &[BufferFormat] {
        &self.formats
    }
}

#[cfg(test)]
mod tests {
    use super::{ComponentKind, FormatTable};

    /// The built-in table keeps four observed rows; a regenerated table losing one fails.
    #[test]
    fn the_builtin_table_loads_and_agrees_with_what_was_measured() {
        let table = FormatTable::builtin().expect("formats");

        // The default, which the disassembler never prints; the generator recovers it by
        // assembling the name and reading the code back.
        let default = table.get(1).expect("code 1 has a meaning");
        assert_eq!(default.name, "BUF_FMT_8_UNORM");
        assert_eq!(default.widths, vec![8]);
        assert_eq!(default.kind, ComponentKind::Unorm);
        assert!(!default.is_plain_words());

        // A plain one, and the arithmetic that makes it plain.
        let float = table.get(22).expect("code 22 has a meaning");
        assert_eq!(float.name, "BUF_FMT_32_FLOAT");
        assert!(float.is_plain_words());
        assert_eq!(float.components(), 1);

        let four = table
            .formats()
            .iter()
            .find(|format| format.name == "BUF_FMT_32_32_32_32_FLOAT")
            .expect("a four-component float format");
        assert!(four.is_plain_words());
        assert_eq!(four.components(), 4);
    }

    /// The invalid code 0 and the reserved high codes resolve to no format.
    #[test]
    fn a_code_with_no_meaning_is_absent_rather_than_approximated() {
        let table = FormatTable::builtin().expect("formats");
        assert!(table.get(0).is_none(), "the invalid code must not resolve");
        for code in [78, 90, 127] {
            assert!(table.get(code).is_none(), "{code} is reserved");
        }
        // Nothing outside the field's range is reachable.
        assert_eq!(
            FormatTable::field(0xFFFF_FFFF),
            (1 << FormatTable::WIDTH) - 1
        );
    }

    /// The format field's shift and width match an assembled instruction.
    #[test]
    fn the_field_position_matches_what_the_assembler_produced() {
        // `tbuffer_load_format_x v0, v1, s[8:11], 0 format:[BUF_FMT_32_FLOAT] idxen`
        // assembles to this first word, and 22 is that format's code.
        assert_eq!(FormatTable::field(0xe8b0_2000), 22);
        // The same instruction with the default format.
        assert_eq!(FormatTable::field(0xe808_2000), 1);
    }
}
