//! The generated status blocks: `status`.

use crate::common::grouped;
use anyhow::{Context, Result};
use orbistoun_service::Service;

/// `paths` - show where orbistoun reads and writes.
/// Where a generated block starts, and what regenerates it.
const BLOCK_OPEN: &str = "<!-- generated by `orbistoun-cli status` - do not edit by hand -->";
/// Where a generated block ends.
const BLOCK_CLOSE: &str = "<!-- end generated -->";

/// The files carrying a generated numbers block. Only the status page: the README states intent
/// and points there, so it carries no counts to go stale.
const GENERATED_IN: &[&str] = &["docs/PROJECT_STATUS.md"];

/// Where the per-title table starts.
const TITLES_OPEN: &str = "<!-- generated by `orbistoun-cli status` - read from compat/ -->";
/// Where it ends.
const TITLES_CLOSE: &str = "<!-- end titles -->";
/// The one file carrying it. The README says how far the project is, not title by title.
const TITLES_IN: &str = "docs/PROJECT_STATUS.md";

/// `status` - the numbers block, generated rather than typed.
///
/// # What is in it and what deliberately is not
///
/// Only numbers this tool can recompute **anywhere**, from what the repository ships. A
/// count that needs a title cannot be one of them: the corpus is not tracked and never will
/// be, so a generated block containing "6 of 6 titles execute guest code" would be
/// unverifiable in CI and would fail for every contributor who has no titles.
///
/// Those numbers still belong in the documentation - they are the most interesting ones -
/// so they live in the prose around the block, where they read as what they are: measured
/// from a run, on one machine, on material not in this repository (D240).
pub(crate) fn cmd_status(service: &Service, write: bool, check: bool) -> Result<()> {
    let block = numbers_block(service);

    if !write && !check {
        println!("{block}");
        return Ok(());
    }

    let mut drifted = Vec::new();
    for file in GENERATED_IN {
        let text = std::fs::read_to_string(file).with_context(|| format!("reading {file}"))?;
        let Some(updated) = splice_block(&text, &block) else {
            // Said out loud rather than skipped. A file that lost its markers would
            // otherwise be silently left behind, holding whatever numbers it last had -
            // which is the drift this exists to stop, with a check that reports success.
            anyhow::bail!("{file} has no generated block - the markers are missing");
        };
        if updated == text {
            continue;
        }
        if write {
            std::fs::write(file, &updated).with_context(|| format!("writing {file}"))?;
            println!("updated {file}");
        } else {
            drifted.push((*file).to_owned());
        }
    }

    // The per-title table, in the one file that carries it. Read from `compat/` rather than
    // typed, because the copy that was typed had been wrong for four days (D329).
    let titles = titles_block(std::path::Path::new("compat"))?;
    let text =
        std::fs::read_to_string(TITLES_IN).with_context(|| format!("reading {TITLES_IN}"))?;
    match splice_between(&text, &titles, TITLES_OPEN, TITLES_CLOSE) {
        None => anyhow::bail!("{TITLES_IN} has no title block - the markers are missing"),
        Some(updated) if updated == text => {}
        Some(updated) => {
            if write {
                std::fs::write(TITLES_IN, &updated)
                    .with_context(|| format!("writing {TITLES_IN}"))?;
                println!("updated {TITLES_IN} (titles)");
            } else {
                drifted.push(format!("{TITLES_IN} (titles)"));
            }
        }
    }

    if check && !drifted.is_empty() {
        anyhow::bail!(
            "the numbers in {} are not what the tool reports - run `orbistoun-cli status --write`",
            drifted.join(", ")
        );
    }
    if write && drifted.is_empty() {
        println!("every generated block is current");
    }
    Ok(())
}

/// The per-title table, read from the records rather than typed.
///
/// # Why this one may be generated when the counts around it may not
///
/// D240 keeps a number out of a generated block when computing it needs a **title**, because
/// the corpus is not tracked and never will be - a block claiming "6 of 6 execute guest code"
/// would fail for every contributor who has none. That reasoning is about needing a *run*.
///
/// `compat/` is committed. Reading it recomputes from what the repository ships, works in CI,
/// and works for somebody with no titles at all - so the rule permits it, and the table it
/// replaces had been wrong for four days: it still said 23 imports and `image+0xafc959` for a
/// title the records put at 25 and `image+0xafcc08` (D329).
///
/// **The honest slot only.** `[experiment]` is a real result about a different question, and a
/// table that mixed the two would be the propped-up number wearing the honest one's clothes.
/// Titles that have one are named underneath, saying what they reached and under what.
fn titles_block(dir: &std::path::Path) -> Result<String> {
    use core::fmt::Write as _;

    let mut honest: Vec<(String, orbistoun_overrides::Status)> = Vec::new();
    let mut helped: Vec<(String, orbistoun_overrides::Status)> = Vec::new();
    let entries = match std::fs::read_dir(dir) {
        Ok(entries) => entries,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            return Ok(format!(
                "{TITLES_OPEN}\n\nNo records yet.\n\n{TITLES_CLOSE}"
            ));
        }
        Err(e) => return Err(e).with_context(|| format!("reading {}", dir.display())),
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().is_none_or(|e| e != "toml") {
            continue;
        }
        let Some(title) = path.file_stem().map(|n| n.to_string_lossy().into_owned()) else {
            continue;
        };
        let text = std::fs::read_to_string(&path)
            .with_context(|| format!("reading {}", path.display()))?;
        let file = orbistoun_overrides::OverrideFile::from_toml(&text)
            .with_context(|| format!("parsing {}", path.display()))?;
        if let Some(status) = file.status {
            honest.push((title.clone(), status));
        }
        if let Some(experiment) = file.experiment {
            helped.push((title, experiment));
        }
    }

    let mut out = String::new();
    let _ = writeln!(out, "{TITLES_OPEN}\n");
    if honest.is_empty() {
        let _ = writeln!(out, "No title has an unassisted record yet.\n");
        let _ = write!(out, "{TITLES_CLOSE}");
        return Ok(out);
    }

    let _ = writeln!(out, "| Title | Reach | Imports | Calls | Standing | Ends |");
    let _ = writeln!(out, "|---|---|---|---|---|---|");
    // Ranked one layer down, so this table and `compat list` cannot disagree about which
    // title is closest to running (D160).
    for (title, status) in orbistoun_overrides::frontier(honest) {
        let _ = writeln!(
            out,
            "| {title} | {} | {} | {} | {}% | `{}` |",
            status.reach.label(),
            status.imports,
            grouped(status.calls),
            status.standing,
            status.outcome
        );
    }

    if !helped.is_empty() {
        helped.sort_by(|a, b| a.0.cmp(&b.0));
        let _ = writeln!(
            out,
            "\nUnder a measured policy - stubs answering by name, so these reach further by\nconstruction and are not comparable with the table above:\n"
        );
        for (title, status) in helped {
            let _ = writeln!(
                out,
                "- **{title}** reached {} imports, ending at `{}`, with {} function{} answered by name",
                status.imports,
                status.outcome,
                status.overrides,
                if status.overrides == 1 { "" } else { "s" }
            );
        }
    }
    let _ = write!(out, "\n{TITLES_CLOSE}");
    Ok(out)
}

/// The block itself, as markdown.
fn numbers_block(service: &Service) -> String {
    use orbistoun_hle::knowledge::Oracle;

    let mut declared = 0_usize;
    let mut implemented = 0_usize;
    // **How many of the declared belong to a library that serves nothing at all.**
    //
    // Without this the headline reads as capability and is not. Before the networking, audio,
    // media, dialog and graphics libraries a title imports were declared, the ratio was
    // 674/647 - **96%** - because the denominator was very nearly "what we had already
    // implemented". Declaring what guests actually ask for moved it to 947/647, and the
    // honest reading of the drop is that the figure started meaning something (D500, D505).
    //
    // Counted by library rather than by symbol: a library with one implementation is being
    // worked on, and a library with none has only had its names written down.
    let mut serves: std::collections::BTreeMap<String, bool> = std::collections::BTreeMap::new();
    for d in service.declared_symbols() {
        declared += 1;
        implemented += usize::from(d.implemented);
        let entry = serves.entry(d.library.clone()).or_default();
        *entry = *entry || d.implemented;
    }
    let names_only: usize = service
        .declared_symbols()
        .iter()
        .filter(|d| !serves.get(&d.library).copied().unwrap_or(false))
        .count();
    let quiet_libraries = serves.values().filter(|served| !**served).count();
    let quiet_plural = if quiet_libraries == 1 { "y" } else { "ies" };

    let knowledge = orbistoun_hle::knowledge::Knowledge::builtin();
    let resting: Vec<String> = [
        Oracle::Published,
        Oracle::Differential,
        Oracle::Measured,
        Oracle::GuestObserved,
        Oracle::Assumed,
    ]
    .iter()
    .map(|o| (o, knowledge.resting_on(*o)))
    .filter(|(_, n)| *n > 0)
    .map(|(o, n)| format!("{n} {}", o.label()))
    .collect();

    let db = orbistoun_nid::SymbolDbFile::builtin();
    // Strongest claim first, in the enum's own order rather than alphabetically by label -
    // the same rule `print_by_tier` follows, so a listing cannot disagree with the type
    // about which claim is stronger.
    let mut split: Vec<String> = [
        orbistoun_nid::Reproducible::FromRepository,
        orbistoun_nid::Reproducible::FromModule,
        orbistoun_nid::Reproducible::FromRun,
        orbistoun_nid::Reproducible::FromHardware,
        orbistoun_nid::Reproducible::OnlyFromItsSource,
    ]
    .iter()
    .map(|tier| {
        let n = db
            .derivations
            .values()
            .filter(|d| d.method.reproducible() == *tier)
            .count();
        (tier, n)
    })
    .filter(|(_, n)| *n > 0)
    .map(|(tier, n)| format!("{n} {}", tier.label()))
    .collect();
    let unaccounted = db.names.len().saturating_sub(db.derivations.len());
    // Always stated, including when it is zero. "Nothing unaccounted for" is the claim the
    // audit exists to support, and a line that appears only when the news is bad reads as
    // absence of the check rather than absence of the problem.
    split.push(format!("{unaccounted} unaccounted"));

    format!(
        "{BLOCK_OPEN}

| | |
|---|---|
| Functions declared / implemented | {declared} / {implemented} |
| Declared in a library that serves nothing | {names_only} across {quiet_libraries} librar{quiet_plural} - names written down, no implementation |
| Recorded behaviours | {} - {} |
| Open questions a hardware probe could settle | {} |
| Symbol database | {} names - {} |

{BLOCK_CLOSE}",
        knowledge.len(),
        resting.join(", "),
        knowledge.open_questions(),
        db.names.len(),
        split.join(", "),
    )
}

/// Replaces whatever sits between the markers, or `None` when they are not both there.
fn splice_block(text: &str, block: &str) -> Option<String> {
    splice_between(text, block, BLOCK_OPEN, BLOCK_CLOSE)
}

/// The same, between whichever markers a block uses.
///
/// Extracted when a second block appeared, rather than copied - two spliceers is two places
/// for "what if the markers are the wrong way round" to be answered differently.
fn splice_between(text: &str, block: &str, open: &str, close: &str) -> Option<String> {
    let start = text.find(open)?;
    let end = text.find(close)? + close.len();
    if end < start {
        return None;
    }
    let mut out = String::with_capacity(text.len());
    out.push_str(&text[..start]);
    out.push_str(block);
    out.push_str(&text[end..]);
    Some(out)
}

#[cfg(test)]
mod tests {
    use super::{BLOCK_CLOSE, BLOCK_OPEN};

    /// A generated block is replaced whole, and its surroundings are left alone.
    #[test]
    fn a_generated_block_is_spliced_between_its_markers() {
        let text = format!(
            "before
{BLOCK_OPEN}
stale
{BLOCK_CLOSE}
after
"
        );
        let fresh = format!(
            "{BLOCK_OPEN}
fresh
{BLOCK_CLOSE}"
        );
        let out = super::splice_block(&text, &fresh).expect("markers are present");
        assert_eq!(
            out,
            format!(
                "before
{fresh}
after
"
            )
        );
        assert!(!out.contains("stale"));
    }

    /// A file that lost its markers is refused rather than silently left behind.
    ///
    /// The failure that matters: a check reporting success over a file it never looked at
    /// is worse than no check, because it is believed (D240).
    #[test]
    fn a_file_without_markers_is_not_quietly_skipped() {
        assert!(super::splice_block("no markers here", "block").is_none());
        assert!(
            super::splice_block(
                &format!(
                    "{BLOCK_OPEN}
unclosed"
                ),
                "block"
            )
            .is_none(),
            "an unterminated block is not a block"
        );
    }
}
