//! The character-classification tables the C runtime hands out.
//!
//! `_Getpctype` and its siblings answer the address of a table the caller indexes:
//! `isalpha(c)` compiles to a load from `_Getpctype()[c]` and a bit test. Each table is
//! installed once in guest-visible memory and every call answers the same pointer. C indexes
//! with a character or `EOF`, so the pointer is the entry for index zero, with a margin below
//! it that `table[-1]` reads. The values come from `data/ctype.toml` (generated by
//! `orbistoun-gen ctype` from an obSCEne hardware capture): the bit layout is the platform C
//! runtime's own and differs from FreeBSD's.

use std::sync::OnceLock;

use orbistoun_core::{GUEST_ARG_REGISTERS, GuestFn};

use crate::{allocate, ptr};

/// Bytes per entry. Each is a `u16`, little-endian, as the capture read them.
const ENTRY_BYTES: usize = 2;

/// The measured tables, parsed once.
fn tables() -> &'static toml::Table {
    static TABLE: OnceLock<toml::Table> = OnceLock::new();
    TABLE.get_or_init(|| {
        include_str!("../data/ctype.toml")
            .parse::<toml::Table>()
            .expect("the measured ctype tables must parse")
    })
}

/// One table's entries and the index its first entry answers for.
fn measured(section: &str) -> (Vec<u16>, i64) {
    let table = tables()
        .get(section)
        .and_then(toml::Value::as_table)
        .unwrap_or_else(|| panic!("data/ctype.toml has no [{section}] section"));
    let first = table
        .get("first_index")
        .and_then(toml::Value::as_integer)
        .unwrap_or_else(|| panic!("[{section}] has no first_index"));
    let entries = table
        .get("entries")
        .and_then(toml::Value::as_array)
        .unwrap_or_else(|| panic!("[{section}] has no entries"))
        .iter()
        .map(|entry| {
            let value = entry
                .as_integer()
                .unwrap_or_else(|| panic!("[{section}] has a non-integer entry"));
            u16::try_from(value)
                .unwrap_or_else(|_| panic!("[{section}] entry {value} does not fit in an entry"))
        })
        .collect();
    (entries, first)
}

/// Installs one table into guest memory, and answers the address of its entry for index
/// zero.
///
/// Allocated through the guest allocator, so the guest's own model of memory accounts for it.
fn install(section: &str) -> u64 {
    let (entries, first) = measured(section);
    let bytes: Vec<u8> = entries
        .iter()
        .flat_map(|entry| entry.to_le_bytes())
        .collect();
    let base = allocate(bytes.len(), ENTRY_BYTES);
    if base == 0 {
        // A table that could not be placed answers null, which the guest can test.
        return 0;
    }
    // SAFETY: `allocate` answered `bytes.len()` writable bytes at `base`, and the source is
    // a local buffer of exactly that length, so the two cannot overlap.
    unsafe { std::ptr::copy_nonoverlapping(bytes.as_ptr(), ptr(base), bytes.len()) };

    // The entry for index zero, the margin's width into the allocation. `first` is negative,
    // so this subtracts.
    let margin = first
        .unsigned_abs()
        .checked_mul(ENTRY_BYTES as u64)
        .expect("the margin of a measured table is small");
    base + margin
}

/// `_Getpctype()` - the classification table.
fn getpctype(_args: &[u64; GUEST_ARG_REGISTERS]) -> u64 {
    static AT: OnceLock<u64> = OnceLock::new();
    *AT.get_or_init(|| install("pctype"))
}

/// `_Getptolower()` - the lower-case mapping.
fn getptolower(_args: &[u64; GUEST_ARG_REGISTERS]) -> u64 {
    static AT: OnceLock<u64> = OnceLock::new();
    *AT.get_or_init(|| install("tolower"))
}

/// `_Getptoupper()` - the upper-case mapping.
fn getptoupper(_args: &[u64; GUEST_ARG_REGISTERS]) -> u64 {
    static AT: OnceLock<u64> = OnceLock::new();
    *AT.get_or_init(|| install("toupper"))
}

/// The implementations this module provides.
pub(crate) fn implementations() -> &'static [(&'static str, GuestFn)] {
    &[
        ("_Getpctype", getpctype),
        ("_Getptolower", getptolower),
        ("_Getptoupper", getptoupper),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The measured classification of a character, by index.
    fn classify(section: &str, index: i64) -> u16 {
        let (entries, first) = measured(section);
        let at = usize::try_from(index - first).expect("inside the table");
        entries[at]
    }

    /// The tables parse and are the shape the generator promised: a margin below zero, and
    /// an entry for every character.
    #[test]
    fn the_measured_tables_cover_every_character_and_a_margin_below_zero() {
        for section in ["pctype", "tolower", "toupper"] {
            let (entries, first) = measured(section);
            assert!(
                first < 0,
                "[{section}] must have entries below zero for EOF"
            );
            let last = first + i64::try_from(entries.len()).expect("a small table") - 1;
            assert!(
                last >= 255,
                "[{section}] stops at {last}, so a character above it would index past the end"
            );
        }
    }

    /// The bits mean what the capture says: `0x20` is the digit bit and `0x400` belongs to the
    /// tab alone, unlike FreeBSD's documented values.
    #[test]
    fn the_classification_bits_are_the_measured_layout_not_the_documented_one() {
        // Digits carry 0x20 and the hexadecimal bit, and not 0x400.
        for digit in i64::from(b'0')..=i64::from(b'9') {
            let mask = classify("pctype", digit);
            assert_eq!(mask & 0x20, 0x20, "{digit} should carry the digit bit");
            assert_eq!(
                mask & 0x400,
                0,
                "{digit} must not carry FreeBSD's digit bit"
            );
        }
        // Upper and lower are distinct bits, and the letters that are also hexadecimal digits
        // carry that bit too.
        assert_eq!(classify("pctype", i64::from(b'A')), 0x3);
        assert_eq!(classify("pctype", i64::from(b'Z')), 0x2);
        assert_eq!(classify("pctype", i64::from(b'a')), 0x11);
        assert_eq!(classify("pctype", i64::from(b'z')), 0x10);
    }

    /// `EOF` is classified as nothing, read from the margin below index zero.
    #[test]
    fn eof_classifies_as_nothing() {
        assert_eq!(classify("pctype", -1), 0);
    }

    /// The case mappings map, and leave alone what has no case.
    #[test]
    fn the_case_tables_map_letters_and_leave_digits_alone() {
        assert_eq!(classify("tolower", i64::from(b'A')), u16::from(b'a'));
        assert_eq!(classify("toupper", i64::from(b'a')), u16::from(b'A'));
        assert_eq!(classify("tolower", i64::from(b'a')), u16::from(b'a'));
        assert_eq!(classify("toupper", i64::from(b'0')), u16::from(b'0'));
    }
}

#[cfg(test)]
mod registration {
    /// The tables are registered with the dispatcher.
    #[test]
    fn the_tables_are_registered_for_dispatch() {
        let all = crate::implementations();
        for name in ["_Getpctype", "_Getptolower", "_Getptoupper"] {
            assert!(
                all.iter().any(|(known, _)| *known == name),
                "{name} is declared but nothing dispatches to it"
            );
        }
    }
}
